name: statemanagement
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  
  flutter_redux: ^0.6.0
  flutter_sparkline: ^0.1.0
  rxdart: ^0.24.1
  equatable: ^1.2.5
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  lipsum: ^1.0.1
  mvc_pattern: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

